CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE chat_messages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id    BIGINT                                  NOT NULL,
    sender_type VARCHAR(255)                            NOT NULL,
    sender_id   BIGINT                                  NOT NULL,
    content     VARCHAR(1000)                           NOT NULL,
    sent_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id)
);

CREATE TABLE delivery_assignments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT                                  NOT NULL,
    driver_id    BIGINT                                  NOT NULL,
    assigned_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    picked_up_at TIMESTAMP WITHOUT TIME ZONE,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    active       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_delivery_assignments PRIMARY KEY (id)
);

CREATE TABLE driver_ratings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    driver_id   BIGINT                                  NOT NULL,
    order_id    BIGINT                                  NOT NULL,
    customer_id BIGINT,
    score       INTEGER                                 NOT NULL,
    comment     VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_driver_ratings PRIMARY KEY (id)
);

CREATE TABLE drivers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id         BIGINT                                  NOT NULL,
    availability_status VARCHAR(255)                            NOT NULL,
    vehicle_type        VARCHAR(255)                            NOT NULL,
    current_latitude    DOUBLE PRECISION,
    current_longitude   DOUBLE PRECISION,
    average_rating      DOUBLE PRECISION,
    total_deliveries    INTEGER,
    CONSTRAINT pk_drivers PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    dish_id    BIGINT                                  NOT NULL,
    dish_name  VARCHAR(255)                            NOT NULL,
    unit_price DECIMAL                                 NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    notes      VARCHAR(255),
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id     BIGINT                                  NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    total_amount    DECIMAL                                 NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    delivered_at    TIMESTAMP WITHOUT TIME ZONE,
    street          VARCHAR(255),
    city            VARCHAR(255),
    postal_code     VARCHAR(255),
    additional_info VARCHAR(255),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

ALTER TABLE delivery_assignments
    ADD CONSTRAINT uc_delivery_assignments_order UNIQUE (order_id);

ALTER TABLE driver_ratings
    ADD CONSTRAINT uc_driver_ratings_order UNIQUE (order_id);

ALTER TABLE drivers
    ADD CONSTRAINT uc_drivers_employeeid UNIQUE (employee_id);

ALTER TABLE chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE delivery_assignments
    ADD CONSTRAINT FK_DELIVERY_ASSIGNMENTS_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES drivers (id);

ALTER TABLE delivery_assignments
    ADD CONSTRAINT FK_DELIVERY_ASSIGNMENTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE driver_ratings
    ADD CONSTRAINT FK_DRIVER_RATINGS_ON_DRIVER FOREIGN KEY (driver_id) REFERENCES drivers (id);

ALTER TABLE driver_ratings
    ADD CONSTRAINT FK_DRIVER_RATINGS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);