CREATE TABLE customers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id     VARCHAR(255)                            NOT NULL,
    loyalty_points  INTEGER,
    total_orders    INTEGER,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    street          VARCHAR(255),
    city            VARCHAR(255),
    postal_code     VARCHAR(255),
    additional_info VARCHAR(255),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_customerid UNIQUE (customer_id);

-- Old numeric customer_id values can't be mapped to the new UUID-string
-- customer_id, so clear out existing orders (and their items) rather
-- than leaving unresolvable rows behind.
DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders);
DELETE FROM delivery_assignments WHERE order_id IN (SELECT id FROM orders);
DELETE FROM orders;

ALTER TABLE orders
DROP COLUMN customer_id;
ALTER TABLE orders
    ADD customer_id VARCHAR(255) NOT NULL;