spring:
  application:
    name: employee-management
  config:
    import: consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
        prefixes: config
        default-context: application
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:employee_management_db}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8084
