package com.esprit.employee.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    USER_NOT_FOUND(NOT_FOUND),
    EMPLOYEE_NOT_FOUND(NOT_FOUND),
    EMAIL_ALREADY_EXISTS(CONFLICT),
    RESTAURANT_ID_REQUIRED(BAD_REQUEST),
    NOTIFICATION_NOT_FOUND(NOT_FOUND),
    INVALID_AUTH_REQUEST(BAD_REQUEST),
    OPTIMISTIC_LOCKING_ERROR(CONFLICT),
    AWS_FAILED_TO_UPLOAD_FILE(INTERNAL_SERVER_ERROR),
    AWS_FAILED_TO_DOWNLOAD_FILE(INTERNAL_SERVER_ERROR),
    INVALID_FILE_TYPE(BAD_REQUEST),
    EMAIL_SEND_FAILED(INTERNAL_SERVER_ERROR),
    DATABASE_ERROR(INTERNAL_SERVER_ERROR),
    VALIDATION_FAILED(BAD_REQUEST),
    MESSAGE_NOT_READABLE(BAD_REQUEST),
    ARGUMENT_TYPE_MISMATCH(BAD_REQUEST),
    MISSING_PARAMETER(BAD_REQUEST),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    MEDIA_TYPE_NOT_SUPPORTED(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    ACCESS_DENIED(FORBIDDEN),
    INTERNAL_ERROR(INTERNAL_SERVER_ERROR);

    private final HttpStatus httpStatus;
}
