spring:
  application:
    name: reservation
  config:
    import: consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
  cloud:
    consul:
      config:
        enabled: true
        format: YAML
        prefixes: config
        default-context: application
