CREATE TABLE staff_assignment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id      BIGINT                                  NOT NULL,
    reservation_code VARCHAR(40)                             NOT NULL,
    reservation_date date                                    NOT NULL,
    start_time       time WITHOUT TIME ZONE                  NOT NULL,
    end_time         time WITHOUT TIME ZONE                  NOT NULL,
    guests_count     INTEGER                                 NOT NULL,
    assigned_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_staff_assignment PRIMARY KEY (id)
);

ALTER TABLE staff_assignment
    ADD CONSTRAINT uq_assignment_reservation_code UNIQUE (reservation_code);

ALTER TABLE staff_assignment
    ADD CONSTRAINT FK_STAFF_ASSIGNMENT_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);